# Generated by Django 5.2.8 on 2026-06-27 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('enseigne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue_app.enseigne')),
            ],
            options={
                'unique_together': {('enseigne', 'date_debut', 'date_fin')},
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_avant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pourcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remise', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('extrait_texte', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('est_sauvegarde', models.BooleanField(default=False)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='catalogue_app.catalogue')),
            ],
        ),
    ]
