# Generated by Django 5.2.8 on 2026-06-30 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('MG', 'MG'), ('Carrefour', 'Carrefour'), ('Carrefour Market', 'Carrefour Market'), ('Carrefour Express', 'Carrefour Express'), ('Aziza', 'Aziza'), ('Anouar', 'Anouar'), ('Géant', 'Géant'), ('Monoprix', 'Monoprix'), ('autre', 'Autre')], default='autre', max_length=50, verbose_name="Nom de l'enseigne")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Enseigne',
                'verbose_name_plural': 'Enseignes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('image_path', models.CharField(blank=True, max_length=255, null=True, verbose_name="Chemin de l'image")),
                ('enseigne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue_app.enseigne', verbose_name='Enseigne')),
            ],
            options={
                'verbose_name': 'Catalogue',
                'verbose_name_plural': 'Catalogues',
                'ordering': ['-date_upload'],
                'unique_together': {('enseigne', 'date_debut', 'date_fin')},
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom (Affiché)')),
                ('nom_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom (FR)')),
                ('nom_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom (AR)')),
                ('marque', models.CharField(blank=True, max_length=255, null=True, verbose_name='Marque')),
                ('prix', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Prix (TND)')),
                ('prix_avant', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Prix avant (TND)')),
                ('pourcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='%')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_2', models.TextField(blank=True, null=True, verbose_name='Description 2')),
                ('description_3', models.TextField(blank=True, null=True, verbose_name='Description 3')),
                ('remise', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Remise (TND)')),
                ('extrait_texte', models.TextField(blank=True, null=True, verbose_name='Texte extrait')),
                ('image_produit', models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='Image du produit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('est_sauvegarde', models.BooleanField(default=False, verbose_name='Sauvegardé')),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='catalogue_app.catalogue', verbose_name='Catalogue')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
    ]
