# Generated by Django 5.2.8 on 2026-07-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='description_user_1',
            field=models.TextField(blank=True, null=True, verbose_name='Description personnalisée 1'),
        ),
        migrations.AddField(
            model_name='produit',
            name='description_user_2',
            field=models.TextField(blank=True, null=True, verbose_name='Description personnalisée 2'),
        ),
    ]
