# Generated by Django 5.2.8 on 2026-06-27 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogue',
            options={'ordering': ['-date_upload'], 'verbose_name': 'Catalogue', 'verbose_name_plural': 'Catalogues'},
        ),
        migrations.AlterModelOptions(
            name='enseigne',
            options={'ordering': ['nom'], 'verbose_name': 'Enseigne', 'verbose_name_plural': 'Enseignes'},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['-created_at'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='date_debut',
            field=models.DateField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='date_fin',
            field=models.DateField(verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='date_upload',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload"),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='enseigne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue_app.enseigne', verbose_name='Enseigne'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Chemin de l'image"),
        ),
        migrations.AlterField(
            model_name='enseigne',
            name='nom',
            field=models.CharField(choices=[('MG', 'MG'), ('Carrefour', 'Carrefour'), ('Carrefour Market', 'Carrefour Market'), ('Carrefour Express', 'Carrefour Express'), ('Aziza', 'Aziza'), ('Anouar', 'Anouar'), ('Géant', 'Géant'), ('Monoprix', 'Monoprix'), ('autre', 'Autre')], default='autre', max_length=50, verbose_name="Nom de l'enseigne"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='catalogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='catalogue_app.catalogue', verbose_name='Catalogue'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='est_sauvegarde',
            field=models.BooleanField(default=False, verbose_name='Sauvegardé'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='extrait_texte',
            field=models.TextField(blank=True, verbose_name='Texte extrait'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom du produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='pourcentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pourcentage de remise'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_avant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix avant remise'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='remise',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant de la remise'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
    ]
