# Generated by Django 5.2.8 on 2026-06-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue_app', '0002_alter_catalogue_options_alter_enseigne_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image_produit',
            field=models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='Image du produit'),
        ),
    ]
