# Generated by Django 5.2.8 on 2026-07-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue_app', '0002_produit_description_user_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='description_user_1',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='description_user_2',
        ),
    ]
