# Generated by Django 5.2.8 on 2026-06-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue_app', '0003_produit_image_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='classe_yolo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Classe YOLO'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Prix (TND)'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_avant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Prix avant remise (TND)'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='remise',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Montant de la remise (TND)'),
        ),
    ]
