# Generated by Django 5.2.8 on 2026-06-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue_app', '0004_produit_classe_yolo_alter_produit_prix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='classe_yolo',
        ),
        migrations.AddField(
            model_name='produit',
            name='description_2',
            field=models.TextField(blank=True, verbose_name='Description 2'),
        ),
        migrations.AddField(
            model_name='produit',
            name='description_3',
            field=models.TextField(blank=True, verbose_name='Description 3'),
        ),
        migrations.AddField(
            model_name='produit',
            name='marque',
            field=models.CharField(blank=True, max_length=255, verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='produit',
            name='nom_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom (AR)'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom (FR)'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='pourcentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='%'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_avant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Prix avant (TND)'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='remise',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Remise (TND)'),
        ),
    ]
