# Generated by Django 5.2.8 on 2026-07-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue_app', '0004_produit_description_user_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='description_user_1',
            field=models.TextField(blank=True, null=True, verbose_name='Description supplémentaire 1'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description_user_2',
            field=models.TextField(blank=True, null=True, verbose_name='Description supplémentaire 2'),
        ),
    ]
