# Generated by Django 5.2.8 on 2026-07-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue_app', '0005_alter_produit_description_user_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='pourcentage',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='%'),
        ),
    ]
