# Generated by Django 5.2.8 on 2026-06-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue_app', '0005_remove_produit_classe_yolo_produit_description_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='nom_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom (FR)'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description_2',
            field=models.TextField(blank=True, null=True, verbose_name='Description 2'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description_3',
            field=models.TextField(blank=True, null=True, verbose_name='Description 3'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='extrait_texte',
            field=models.TextField(blank=True, null=True, verbose_name='Texte extrait'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='marque',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Marque'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom (Affiché)'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom (AR)'),
        ),
    ]
