# Generated by Django 5.2.8 on 2026-07-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue_app', '0006_alter_produit_pourcentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Note (ex: Saint Valentin, Noël, Eid...)'),
        ),
    ]
