# Generated by Django 5.2.8 on 2026-07-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue_app', '0007_catalogue_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='description_3',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='description_user_1',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='description_user_2',
        ),
        migrations.AddField(
            model_name='produit',
            name='desc_1',
            field=models.TextField(blank=True, null=True, verbose_name='Desc 1'),
        ),
        migrations.AddField(
            model_name='produit',
            name='desc_2',
            field=models.TextField(blank=True, null=True, verbose_name='Desc 2'),
        ),
        migrations.AddField(
            model_name='produit',
            name='desc_3',
            field=models.TextField(blank=True, null=True, verbose_name='Desc 3'),
        ),
        migrations.AddField(
            model_name='produit',
            name='note_1',
            field=models.TextField(blank=True, null=True, verbose_name='Note 1'),
        ),
        migrations.AddField(
            model_name='produit',
            name='note_2',
            field=models.TextField(blank=True, null=True, verbose_name='Note 2'),
        ),
    ]
