# Generated by Django 5.2.8 on 2026-07-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue_app', '0010_journalaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalaction',
            options={'ordering': ['-date_action']},
        ),
        migrations.AlterField(
            model_name='journalaction',
            name='action',
            field=models.CharField(choices=[('ajout', 'Ajout'), ('modification', 'Modification'), ('suppression', 'Suppression')], max_length=20),
        ),
        migrations.AlterField(
            model_name='journalaction',
            name='catalogue_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='journalaction',
            name='date_action',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='journalaction',
            name='produit_nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
