# Generated by Django 5.2.8 on 2026-07-25 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue_app', '0011_alter_journalaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalaction',
            name='catalogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_journal', to='catalogue_app.catalogue', verbose_name='Catalogue'),
        ),
    ]
