# Generated by Django 5.2.8 on 2026-07-27 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue_app', '0012_journalaction_catalogue'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemin', models.CharField(max_length=255, verbose_name="Chemin de l'image")),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre (page)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue_app.catalogue', verbose_name='Catalogue')),
            ],
            options={
                'verbose_name': 'Image du catalogue',
                'verbose_name_plural': 'Images du catalogue',
                'ordering': ['ordre', 'created_at'],
            },
        ),
    ]
